### ISSUE TITLE
не видит устройства в HA

### ISSUE THREAD

**Issue by czech777** [AlexxIT/AlexxIT#1]
у меня происходят странности со шлюзами v3
первый шлюз подключил к НА, пробросились блютуз светильники, но zigbee (кнопка и датчик температуры не видятся)
я удалил шлюз из НА и из михом, после в михом подключил, в НА прописывается но вообще нет устройств. пробовал на другой системе прописать, тоже самое
все это было на даче (192.168.10.*)  удалил, прописал уже в квартире (192.168.31.*) в михом все норм а в НА тоже самое, нет устройств.
взял второй шлиз v3, на даче и все нормально отображается в НА, взял третий прописал в квартире и результат нулевой (т.е в НА не видит устройств)
может есть какие-то версии шлюза v3 не совместимые с интеграцией? (первый и третий были куплены одновременно, второй позже)

**Comment by AlexxIT** [comment]
Новые прошивки не совместимы с интеграцией. Это написано в документации
https://github.com/AlexxIT/XiaomiGateway3
